# CMake generated Testfile for 
# Source directory: C:/Users/rohit/Documents/application/tube_sealer/packages/tube_sealer_native/test
# Build directory: C:/Users/rohit/Documents/application/tube_sealer/packages/tube_sealer_native/build-test/test
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(test_ring_buffer "C:/Users/rohit/Documents/application/tube_sealer/packages/tube_sealer_native/build-test/test/Debug/test_ring_buffer.exe")
  set_tests_properties(test_ring_buffer PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/rohit/Documents/application/tube_sealer/packages/tube_sealer_native/test/CMakeLists.txt;48;add_test;C:/Users/rohit/Documents/application/tube_sealer/packages/tube_sealer_native/test/CMakeLists.txt;52;tsn_add_test;C:/Users/rohit/Documents/application/tube_sealer/packages/tube_sealer_native/test/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(test_ring_buffer "C:/Users/rohit/Documents/application/tube_sealer/packages/tube_sealer_native/build-test/test/Release/test_ring_buffer.exe")
  set_tests_properties(test_ring_buffer PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/rohit/Documents/application/tube_sealer/packages/tube_sealer_native/test/CMakeLists.txt;48;add_test;C:/Users/rohit/Documents/application/tube_sealer/packages/tube_sealer_native/test/CMakeLists.txt;52;tsn_add_test;C:/Users/rohit/Documents/application/tube_sealer/packages/tube_sealer_native/test/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(test_ring_buffer "C:/Users/rohit/Documents/application/tube_sealer/packages/tube_sealer_native/build-test/test/MinSizeRel/test_ring_buffer.exe")
  set_tests_properties(test_ring_buffer PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/rohit/Documents/application/tube_sealer/packages/tube_sealer_native/test/CMakeLists.txt;48;add_test;C:/Users/rohit/Documents/application/tube_sealer/packages/tube_sealer_native/test/CMakeLists.txt;52;tsn_add_test;C:/Users/rohit/Documents/application/tube_sealer/packages/tube_sealer_native/test/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(test_ring_buffer "C:/Users/rohit/Documents/application/tube_sealer/packages/tube_sealer_native/build-test/test/RelWithDebInfo/test_ring_buffer.exe")
  set_tests_properties(test_ring_buffer PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/rohit/Documents/application/tube_sealer/packages/tube_sealer_native/test/CMakeLists.txt;48;add_test;C:/Users/rohit/Documents/application/tube_sealer/packages/tube_sealer_native/test/CMakeLists.txt;52;tsn_add_test;C:/Users/rohit/Documents/application/tube_sealer/packages/tube_sealer_native/test/CMakeLists.txt;0;")
else()
  add_test(test_ring_buffer NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(prop_ring_buffer "C:/Users/rohit/Documents/application/tube_sealer/packages/tube_sealer_native/build-test/test/Debug/prop_ring_buffer.exe")
  set_tests_properties(prop_ring_buffer PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/rohit/Documents/application/tube_sealer/packages/tube_sealer_native/test/CMakeLists.txt;48;add_test;C:/Users/rohit/Documents/application/tube_sealer/packages/tube_sealer_native/test/CMakeLists.txt;57;tsn_add_test;C:/Users/rohit/Documents/application/tube_sealer/packages/tube_sealer_native/test/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(prop_ring_buffer "C:/Users/rohit/Documents/application/tube_sealer/packages/tube_sealer_native/build-test/test/Release/prop_ring_buffer.exe")
  set_tests_properties(prop_ring_buffer PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/rohit/Documents/application/tube_sealer/packages/tube_sealer_native/test/CMakeLists.txt;48;add_test;C:/Users/rohit/Documents/application/tube_sealer/packages/tube_sealer_native/test/CMakeLists.txt;57;tsn_add_test;C:/Users/rohit/Documents/application/tube_sealer/packages/tube_sealer_native/test/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(prop_ring_buffer "C:/Users/rohit/Documents/application/tube_sealer/packages/tube_sealer_native/build-test/test/MinSizeRel/prop_ring_buffer.exe")
  set_tests_properties(prop_ring_buffer PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/rohit/Documents/application/tube_sealer/packages/tube_sealer_native/test/CMakeLists.txt;48;add_test;C:/Users/rohit/Documents/application/tube_sealer/packages/tube_sealer_native/test/CMakeLists.txt;57;tsn_add_test;C:/Users/rohit/Documents/application/tube_sealer/packages/tube_sealer_native/test/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(prop_ring_buffer "C:/Users/rohit/Documents/application/tube_sealer/packages/tube_sealer_native/build-test/test/RelWithDebInfo/prop_ring_buffer.exe")
  set_tests_properties(prop_ring_buffer PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/rohit/Documents/application/tube_sealer/packages/tube_sealer_native/test/CMakeLists.txt;48;add_test;C:/Users/rohit/Documents/application/tube_sealer/packages/tube_sealer_native/test/CMakeLists.txt;57;tsn_add_test;C:/Users/rohit/Documents/application/tube_sealer/packages/tube_sealer_native/test/CMakeLists.txt;0;")
else()
  add_test(prop_ring_buffer NOT_AVAILABLE)
endif()
subdirs("../_deps/googletest-build")
subdirs("../_deps/rapidcheck-build")
